### ISSUE TITLE
括弧で囲まれた文章が一文として判定される

### ISSUE THREAD

**Issue by HBonsai** [textlint-ja/textlint-rule-no-doubled-conjunctive-particle-ga#19]
![image](https://user-images.githubusercontent.com/10624619/157427071-17c41bcf-5980-43be-8272-121407f34e27.png)

「」や各種括弧内の文章が"。"で文を区切っているにもかかわらず一文として判定され、別々の文でも"が"を使っていると指摘対象になってしまいます。小説を書くときは文章を「」で囲うことは珍しくないため、囲っていても通常の文と同様に扱っていただけると助かります。

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-no-doubled-conjunctive-particle-ga/releases/tag/v2.0.5
で修正しました
